### ISSUE TITLE
do you know any ways of making a blur like this for DirectX 11?

### ISSUE THREAD

**Issue by pgr4ham** [3r4y/imgui-blur-effect#2]

**Comment by 3r4y** [comment]
I will update for dx11, dx12 and opengl soon.

**Comment by ambiennt** [comment]
> I will update for dx11, dx12 and opengl soon.

Thank you! Looking forward to it. Currently stuck on a Dx11 implementation, I have been unable to find good examples elsewhere.

**Comment by BaiFeng666** [comment]
> 我将很快更新 dx11、dx12 和 opengl。

Looking forward to it!! Thanks

**Comment by TheBarii** [comment]
> I will update for dx11, dx12 and opengl soon.

When will this happen? I really need dx11 and dx12 though I don't have the skills for it. Please?

**Comment by 3r4y** [comment]
I finally had some free time and completed the project
here it is.
https://github.com/3r4y/ImGuiGaussianBlur

**Comment by BaiFeng666** [comment]
> I finally had some free time and completed the project here it is. https://github.com/3r4y/ImGuiGaussianBlur

nice completed, but how to achieve real-time access to the Texture memory of a certain area in the game? (It's like taking a screenshot of an area in a loop, then turning it into a blur image and drawing it)
